pterm/pterm

.github/FUNDING.yml
=> docs: add sponsor button

progressbar.go
=> feat: add `Progressbar`

_examples/progressbar/main.go, progressbar.go
=> feat: make progressbar configurable

_examples/progressbar/main.go, progressbar.go
feat: add `BarFiller` to `Progressbar`
=> feat: add `BarFiller` to `Progressbar`

_examples/section-default/main.go, header_printer.go, pterm_test.go, section_printer.go
=> Add section printer

CONTRIBUTING.md, _examples/paragraph-custom/main.go, _examples/paragraph/main.go, paragraph_printer.go, section_printer.go
=> feat: add `ParagraphPrinter`

pterm_benchmark_test.go, pterm_test.go
=> Add tests for spinner and Sprint -> Print

_examples/demo/main.go
=> docs(demo): add `SectionPrinter` to demo

CONTRIBUTING.md, _examples/table/main.go, table_printer.go
=> feat: add `TablePrinter`

internal/map_range_to_range.go, internal/map_range_to_range_test.go, rgb.go
Added a color fade function and `RBG`.
Closes: #29
=> feat: add color fade function and `RBG`

progressbar.go, rgb.go
Implemented the color fade method to the `Progressbar`.
=> feat: implement color fade to `Progressbar`

_examples/print-color-fade/main.go
=> feat: add color fade example

errors.go, pterm_test.go, rgb.go
Closes: #40
Added a HEX to RGB converter in `RGB`.
=> feat: add HEX to RGB converter in `RGB`

table_printer.go
=> feat: add csv table support

.github/pull_request_template.md
Adds a simple to do checklist to PR template.
Fixes #51
=> docs: add to do list to PR template

progressbar.go
Added option to remove Progress Bar when it's done.
Fixes #11
=> feat(progressbar): add RemoveWhenDone

ci/main.go
Better error handling in CI System #47
* Change the fatal for Panic to stop execution
* Get the combined output of executing cmd commands to show the actual error of the go routines execution
Signed-off-by: FabianBG <f4b4g3@gmail.com>
* Change the fatal for Panic to stop execution
* Get the combined output of executing cmd commands to show the actual error of the go routines execution
- [X ] New Feature
Fixes #47
- [X ] I tested my changes
=> ci: better error handling in CI System

_examples/print-color-fade/main.go
Changed the color fade demo to fade from cyan to magenta
Fixes #
=> docs(examples): color fade demo, fade from cyan to magenta

progressbar.go, progressbar_test.go
Changed Line to bar
I tested it and I think it works but double check because I am really new to go.
Line is now defined as bar
=> refactor: change `LineCharacter` to `BarCharacter`

_examples/print-color-fade-multiple/main.go, rgb.go, rgb_test.go
feat: add fade from one RGB over several RGBs to another RGB
Fixes #80
=> feat: add fade from one RGB over several RGBs to another RGB

README.md
Add Features list to readme.
Fixes #83
=> docs(readme): add features list to README

_examples/print-color-fade-multiple/main.go
docs(examples): change color fade multiple example
=> docs(examples): change color fade multiple example

README.md, _examples/prefix/main.go, internal/test_utils.go, prefix_printer.go, prefix_printer_test.go, pterm.go, pterm_test.go, theme.go, theme_test.go
=> feat: add support for enabling and disabling debug messages

_examples/bulletlist/main.go, _examples/demo/main.go, bulletlist_printer.go, bulletlist_printer_test.go
add a tree list printer
Fixes #
=> feat: add tree list

_examples/disable-color/main.go, color.go, color_test.go
Add option to disable and enable colors
Fixes #95
=> feat: add option to disable and enable colors

_examples/demo/main.go, _examples/tree/main.go, tree_printer.go, tree_printer_test.go
Added more spacing between levels and added `Tree` to demo.
=> refactor(tree): add more spacing between levels

theme.go
Changed `ProgressbarBarStyle` FgLightCyan to FgCyan color in `Theme` to match the style with the other background colors i.e. `Header`.
Fixes #
=> refactor(theme): change `ProgressbarBarStyle` to `FgCyan`

_examples/disable-color/main.go
Added `Tree` to demo disable color.
=> docs(examples): update `disable-color` example

CONTRIBUTING.md, bigtext_printer.go, bulletlist_printer.go, bulletlist_printer_test.go, interface_live_printer.go, interface_renderable_printer.go, internal/test_utils.go, progressbar.go, progressbar_test.go, pterm_benchmark_test.go, spinner.go, table_printer.go, tree_printer.go
BREAKING CHANGE: Interface of `RenderablePrinter` and `LivePrinter` changed.
Closes: #99
Fixes #99
=> feat: make printers return errors

README.md, _examples/center/main.go, center_printer.go, center_printer_test.go
=> feat: add `CenterPrinter`

_examples/panel/main.go, bigtext_printer.go, internal/max_text_width.go, panel_printer.go, panel_printer_test.go
=> feat: add `PanelPrinter`

panel_printer.go, panel_printer_test.go
Added an option to make columns the same length.
Fixes #126
=> feat: sync panels vertically

panel_printer.go, panel_printer_test.go
Added an option to make a padding beneath `panel`.
Fixes #128
=> feat: add an option to make a padding beneath `panel`

panel_printer.go, panel_printer_test.go
Added invalid check for `padding` in `panel`.
Fixes #130
=> fix: add invalid check for `padding` in `panel`

_examples/panel/main.go, header_printer.go, internal/max_text_width.go, panel_printer.go
Fixed a bug described in #136
Fixes #136
=> fix(panel): fix output when input is colored

CONTRIBUTING.md
Changed examples to return error. Some minor naming changes.
Fixes #144
=> docs(contributing): change examples to return error

_examples/box/main.go, box_printer.go, box_printer_test.go
=> feat(boxprinter): add `WithHorizontalString` to `BoxPrinter`

README.md
Updated the readme with the new main features.
Fixes #
=> docs(readme): update readme with new main features

.gitpod.yml, README.md
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.
=> chore(gitpod): add gitpod support

color.go
Makes `Color` implement `TextPrinter`
Fixes #
=> fix(color): make color implement `TextPrinter`

_examples/box/main.go, _examples/demo/main.go
=> Updated examples

header_printer.go
=> fix inline color in `Header`

ci/terminal-theme.txt
=> ci: change color scheme for rendered examples

ci/terminal-theme.txt
This reverts commit 09f3068d
Fixes #
=> Revert "ci: change color scheme for rendered examples"

_examples/area/main.go, area_printer.go, area_printer_test.go, docs/_sidebar.md, docs/contributing/writing-documentation-template.md, docs/docs/functions.md, docs/docs/printer/area.md, go.mod, go.sum
Adds an updatable area.
Fixes #194
=> Add an updatable area

basic_text_printer.go, basic_text_printer_test.go, box_printer.go, box_printer_test.go, center_printer.go, center_printer_test.go, color.go, color_test.go, header_printer.go, header_printer_test.go, interface_text_printer.go, paragraph_printer.go, paragraph_printer_test.go, prefix_printer.go, print.go, print_test.go, rgb.go, rgb_test.go, section_printer.go, section_printer_test.go
Added `PrintOnError` for all printers and interface.
Fixes #198
=> feat: add `PrintOnError` for all printers and interface

header_printer.go
Fix header with multiple lines.
Fixes #209
=> Fix header with multiple lines

print.go, spinner_printer.go, spinner_printer_test.go
print lines above active spinners
Fixes #211
=> feat: print lines above active spinners

_examples/box/main.go, box_printer.go, box_printer_test.go, docs/docs/printer/box.md, internal/title_in_line.go
Added a title & title position to `BoxPrinter`.
Fixes #221
=> feat(boxprinter): add title & title position to `BoxPrinter`

box_printer_test.go, center_printer_test.go, color.go, header_printer_test.go, tree_printer_test.go
Fixed multiline style coloring.
Fixes #229
=> fix(style): fix multiline style coloring

docs/docs/printer/spinner.md, spinner_printer.go, spinner_printer_test.go, theme.go
Add option to show a timer on spinners.
Fixes #79
=> Add option to show a timer on spinners.

docs/docs/printer/prefix.md, prefix_printer.go, prefix_printer_test.go
Added `LineNumberOffset` to `PrefixPrinter`.
Fixes #256
=> Added `LineNumberOffset` to `PrefixPrinter`

area_printer_test.go
Removed `AreaPrinter` test output
=> test: removed `AreaPrinter` test output

.vscode/extensions.json
=> chore: removed `.vscode` folder

.github/workflows/animator.yml
=> ci: fixed automatic docs updates

spinner_printer.go
Fix line didn't clear properly.
Fixes #374
=> fix(spinner): fix line didn't clear properly

interactive_textinput_printer.go
Fixed no newline on `TextinputPrinter`
=> Fixed no newline on `TextinputPrinter`

.github/workflows/go.yml
Automated tests were having some problems running on MacOS because there were too many file descriptors
Fixes #https://github.com/pterm/pterm/issues/410
Just tell me if there's anything else I need to do.
=> chore(ci): remove macos from matrix

.github/workflows/go.yml, _examples/table/boxed/main.go, _examples/table/demo/main.go, _examples/table/multiple-lines/main.go, _examples/table/right-alignment/main.go, go.mod, go.sum, table_printer.go, table_printer_test.go
=> feat(table): multiline support for table printer

table_printer.go
=> fix(table): fixed panic when multiple lines contained color in a single column

heatmap_printer_test.go
Added some basic tests for the heatmap printer.
> #472
=> Add basic tests to heatmap printer

pterm.go
=> fix: don't intercept os signals

interactive_textinput_printer.go, interactive_textinput_printer_test.go
=> fix(interactive-textinput): panic at interactive_textinput_printer & edit value in-place

_examples/spinner/demo/main.go
=> Fixed documentation error

prefix_printer.go
=> fix: use rune len

prefix_printer.go, prefix_printer_test.go, print.go, progressbar_printer.go, spinner_printer.go, spinner_printer_test.go, utils_test.go
Fixes prints while a progressbar or spinner is running.
Fixes #689
=> fix(progressbar/spinner): fix print while progressbar / spinner is running

box_printer.go, box_printer_test.go
=> feat: adding more padding setters for BoxPrinter

_examples/interactive_multiselect/custom-filter-placeholder/ci.go, _examples/interactive_multiselect/custom-filter-placeholder/main.go, _examples/interactive_select/custom-filter-placeholder/ci.go, _examples/interactive_select/custom-filter-placeholder/main.go, interactive_multiselect_printer.go, interactive_select_printer.go
add filter input placeholder to multiselect and select printers
=> feat(interactive_select): add filter input placeholder to multiselect and select printers

internal/center_text.go, internal/longest_line.go, internal/max_text_width.go, internal/max_text_width_test.go, internal/utils.go, print.go
Enhance RemoveColorFromString to also strip OSC 8 hyperlinks
=> fix(print): enhance RemoveColorFromString to also strip OSC 8 hyperlinks
