pterm/pterm

prefix_printer.go
Adds a `Fatal` option to `PrefixPrinter`
=> feat: add fatal to `PrefixPrinter`

print.go, pterm.go, pterm_test.go
Now we can disable output using `pterm.DisableOutput = false` for using with quiet mode
Fixes #31
=> feat: add ability to disable output

_examples/demo/main.go
Changed the length of the tree example in the demo to fit in one window.
=> docs(examples): change length of tree example in demo

_examples/demo/main.go
Changed the color of `BigText` P in PTerm to FgLightCyan to match the color of the other letters.
=> docs(examples): change color of `BigLetter` P of PTerm to `FgLightCyan`

print.go, print_test.go, pterm.go, pterm_test.go
BREAKING CHANGE: The global variable `DisableOutput` was renamed to `Output`.
Fixes #
=> feat: add `DisableOutput()` and `EnableOutput()`

center_printer.go
BREAKING CHANGE: make centerprinter func `WithCenterEachLineSeparately` return a pointer of centerprinter
Made centerprinter func `WithCenterEachLineSeparately` return a pointer.
Fixes #114
=> fix(centerprinter): make centerprinter func return pointer

.idea/vcs.xml, basic_text_printer.go, color.go, header_printer.go, paragraph_printer.go, prefix_printer.go, rgb.go, section_printer.go
Corrected behavior of `Println` in every `TextPrinter`.
Fixes #160
=> fix: correct `pterm.Println()` behaviour to fit to `fmt.Println()`

_examples/prefix/main.go, prefix_printer.go, prefix_printer_test.go
Adds an option to `PrefixPrinter`, which outputs the line number and filename, where the `PrefixPrinter` is used.
=> feat(prefixprinter): Add option to show line number of caller

bigtext_printer.go, bigtext_printer_test.go
I've noticed that numbers 5 and 9 are higher than others. Made a test and also found two more symbols with higher heights.
Also added two more symbols - is it ok to include them in the same PR?
Fixes #
=> fix(bigtext): fix height of some characters #180

table_printer.go
Calculation of the width of the columns by the number of characters (runes), not bytes 
=> Column width in table with UTF-8 non ASCII

docs/docs/printer/prefix.md, prefix_printer.go, prefix_printer_test.go
Adds the function `PrintIfError` to `PrefixPrinter`, which only prints if the given error is not nil
=> Add `PrintIfError` to `PrefixPrinter`

prefix_printer.go, prefix_printer_test.go
Fix `pterm.Fatal.Printfln` not panicking because `checkFatal` was not checked.
Fixes #196
=> fix: fix `pterm.Fatal.Printfln` not panicking

prefix_printer.go, prefix_printer_test.go
Change `pterm.Error` default to no line number shown.
Fixes #
=> refactor(prefix): `pterm.Error` default no line number shown

table_printer.go, table_printer_test.go
Add an option to the `TablePrinter`, which adds a box around it.
Fixes #225
=> feat(table): add `Boxed` option

spinner_printer.go, spinner_printer_test.go
Updated `p.Text` before the call to `Printo` so that the new text gets printed instead of what was previously stored.
`SpinnerPrinter`.
Fixes #227
=> fix(spinner): Override previous text in `UpdateText`

barchart.go, barchart_test.go
Fixes #233
The second argument to `strings.Repeat()` cannot be negative, and this causes a panic when the bar chart is rendered horizontally with zero values. This PR ensures that the argument to `strings.Repeat()` can no longer be zero this preventing the panic.
Fixes #233
=> fix(bar chart): fix panic when rendering empty horizontal bar chart

.gitignore, utils_test.go
- replaced stdout capture with an in-memory buffer
- fixed non-windows platforms
- possibly increased the speed of tests (1.650s)
Fixes https://github.com/pterm/pterm/issues/289
=> ci: fixed flaky tests on linux/macos

.github/workflows/go.yml, table_printer_test.go
Added matrix tests for windows, linux and darwin.
=> ci: added matrix tests for windows, linux and darwin

putils/stats.go
=> refactor(putils): Improved styling

bigtext_printer.go, internal/utils.go
feat: use fallback color in `BigTextPrinter` when `RGB` is not supported
=> feat: use fallback color in `BigTextPrinter` when `RGB` is not supported

_examples/table/demo/main.go, table_printer.go
fixed column length calculation for Chinese strings
Fixes #377
=> fix(table): fixed column length calculation for Chinese strings

_examples/spinner/demo/main.go, spinner_printer.go, spinner_printer_test.go
In addition to Success/Warning/Failure message style in Spinner, this PR adds Info style.
For example, this allows to customize the new InfoPrinter with a "No change" printer, as a "no change" state is now common in idem potency systems.
Spinner example is update to:
Fixes #
=> Adds InfoPrinter in SpinnerPrinter

.golangci.yml, interactive_confirm_printer.go, interactive_confirm_printer_test.go
The lib allows specifying the confirmation and rejection text but hardcodes the answers to yes or no, this aims to fix that.
Fixing this issue helps with internationalisation, for example, in most Latin based languages the suffix should be `[s/N]` instead of `[y/N]` (in French it would probably be `[o/N]`)
**Note**: I've disabled the `gocritic` complaint regarding `preferDecodeRune` as I don't think it would make sense to use `utf8.DecodeRuneInString` in this situation.
Ideally, `gocritic` should allow disabling the rule for a single line with a comment in the code, but that doesn't seem to be possible at the moment...
Interactive Confirm Printer
=> fix: the interactive confirm answers should match the confirm/reject text

interactive_multiselect_printer.go
Fixes an index out of range bug in `InteractiveMultiselectPrinter`.
Fixes #392
=> fix index out of range in InteractiveMultiselectPrinter

interactive_textinput_printer.go
=> fix(textinput): fixed overwriting the default values

internal/center_text.go, putils/README.md, putils/center_text.go, putils/center_text_test.go
=> feat(putils): add `CenterText` in putils

interactive_confirm_printer.go
Analogous to commit be556291c6c6263a469069231cb2e9b408a8453c.
=> fix: Make sure the confirm printer can clean up after Ctrl+C

interactive_select_printer.go
Use the correct given style style for the InteractiveSelectPrinter instead of the default theme.
- [ v] Bug Fix
Fixes #
- [x ] I tested my changes
- [ x] I have commented every method that I created/changed
=> Use the correct given style for the `InteractiveSelectPrinter` instead of the default theme.

spinner_printer.go
When RawOuput is set we do not want to print the spinner but without
sleep the refresh delay an very tight loop is run causing 100% CPU
on one goroutine.
Fixes #461
=> If printing nothing for spinner, still sleep to avoid CPU usage

_examples/table/boxed/main.go, _examples/table/demo/main.go, _examples/table/multiple-lines/main.go, _examples/table/right-alignment/main.go
=> example(table): fixed text that was too long to be displayed in the animation

.github/workflows/go.yml, .github/workflows/golangci.yml
- Bump the `actions/checkout` version from `v2` (Node 12) to `v3` (Node 16).
- Bump the `actions/setup-go` version from `v2` (Node 12) to `v4` (Node 16).
- Bump the `codecov/codecov-action` version from `v1` to `v3`.
This PR fixes the Node 12 deprecation warnings displayed under Annotations in Actions runs, as all actions have been updated to Node 16.
Workflows using `go.yml` and `golangci.yml`
=> ci(workflows): Bump actions version, fix Node 12 deprecation warnings

_examples/interactive_textinput/password/ci.go, _examples/interactive_textinput/password/main.go, interactive_textinput_printer.go, interactive_textinput_printer_test.go
Adds `WithMask(string)` to `TestInteractiveTextInputPrinter` for prompting for secrets (such as passwords, API tokens, etc.)
It gives user feedback by showing `mask` characters instead of the actual characters.
Inspired by the [password](https://github.com/go-survey/survey#password) prompter from [go-survey/survey](https://github.com/go-survey/survey)
```go
result, _ := pterm.DefaultInteractiveTextInput.WithMask("*").Show()
```
=> feat: add optional mask to InteractiveTextInputPrinter for prompting for secrets/passwords/tokens

progressbar_printer.go, progressbar_printer_test.go
I have modified the ProgressbarPrinter to print the filler starting from the beginning.
Fixes #495
=> add: progress bar filler from start

interactive_multiselect_printer.go
Refactor `WithFilter()` method on `interactive_multiselect_printer.go` file.
Every boolean option on project used `WithBoolean` method on internals package except this file.
Fixes #
=> refactor: use WithBoolean on multiselect printer

go.mod, go.sum
This project no longer builds without go 1.21 due to use of `log/slog`.
From https://go.dev/ref/mod: `The go directive sets the minimum version of Go required to use this module.`
Fixes #
=> fix: upgrade Go version to 1.21

interactive_multiselect_printer.go, interactive_multiselect_printer_test.go, interactive_select_printer.go, interactive_select_printer_test.go
- Recreate https://github.com/pterm/pterm/pull/561
- This PR adds additional key binding Ctrl-p/Ctrl-n to move up and down in select/multiselect since these keys are quite commonly used
Fixes #
=> feat(select): added additional navigation keys

heatmap_printer.go
Fixed a bug regarding the length of the box of the legend.
heatmap printer
Fixes #582
=> fix(heatmap): fix bug legend was not fully boxed

interactive_continue_printer.go, interactive_textinput_printer_test.go, internal/cancelation_signal.go, internal/cancelation_signal_test.go, internal/exit.go, internal/exit_test.go
Adding a default behavior to cancelation signals when they are nil.  
When a function is not provided it uses `os.Exit(1)` which is expected as default behavior.
Using an `internal.Exit` so we can mock `os.Exit` functionality for testing
Updated a test that was terminated by `os.Exit` behavior
Fixes https://github.com/pterm/pterm/issues/592
=> fix: exit on `ctrl+c` in interactive printers by default

errors.go, logger.go, logger_test.go
Fixes https://github.com/pterm/pterm/issues/628. New output:
pterm logger's `Args` method.
Fixes #628
=> fix: graceful handling of odd args

progressbar_printer.go, spinner_printer.go
=> feat: support timer modifactions on `Spinner` and `Progressbar`

multi_live_printer.go, multi_live_printer_test.go
When `parts` consists of all empty strings, this loop underruns with the following panic:
```
panic: runtime error: index out of range [-1] [recovered]
panic: runtime error: index out of range [-1]
goroutine 9 [running]:
[...]
panic({0x6b3ee0?, 0xc0000204b0?})
/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/pterm/pterm.(*MultiPrinter).getString(0xc0000d6d00?)
/workspace/pterm/multi_live_printer.go:67 +0x1c6
```
This commit fixes that by checking for the condition and using an empty string if there is nothing else available.
=> Fix array out of bounds error in MultiPrinter.getString()

spinner_printer.go
The spinner was printing an extra newline character upon starting, which caused layout issues in the terminal. The root cause is an unconditional `Fprintln` call in the `Start` method.
This removes the extra `Fprintln` to resolve the issue.
Fixes  #731
=> fix(spinner): remove extra newline on start
